[versions]
androidGradlePlugin = "8.12.3"
dom4j = "2.2.0"
kotlin = "2.2.20"
kotlinComposeCompilerPlugin = "2.1.20"
ksp = "2.2.20-2.0.3"
materialIconsCore = "1.7.8"
runtime = "1.9.2"
vico = "2.2.0"
hilt = "2.57.2"
androidXHilt = "1.3.0"
nav = "2.9.5"
coreKtx = "1.17.0"
splashscreen = "1.0.1"
lifecycle = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.09.01"
composeMaterial3 = "1.4.0"
composeUi = "1.9.2"
composeAnimationGraphics = "1.9.2"
coil = "2.7.0"
jsoup = "1.21.2"
gson = "2.13.2"
markdown = "0.5.7"
ketch = "2.0.5"
room = "2.8.1"
work = "2.10.5"
desugar = "2.1.5"
junit = "4.13.2"
swipe = "1.3.0"
serializationJson = "1.9.0"
kotlinxCoroutinesCore = "1.10.2"
zoomableImageCoil = "0.17.0"
composeShimmer = "1.3.3"
foundation = "1.9.2"

[libraries]
androidx-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "materialIconsCore" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
dom4j = { module = "org.dom4j:dom4j", version.ref = "dom4j" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "androidXHilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidXHilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidXHilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidXHilt" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
kotlin-compose-compiler-plugin = { module = "org.jetbrains.kotlin:kotlin-compose-compiler-plugin", version.ref = "kotlinComposeCompilerPlugin" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose-android", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeUi" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUi" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics-android", version.ref = "composeAnimationGraphics" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "markdown" }
ketch = { module = "com.github.khushpanchal:Ketch", version.ref = "ketch" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
junit = { module = "junit:junit", version.ref = "junit" }
swipe = { module = "me.saket.swipe:swipe", version.ref = "swipe" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "zoomableImageCoil" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }

[plugins]
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose_compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android_application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
google_dagger_hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google_ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "androidGradlePlugin" }
