[versions]
androidGradlePlugin = "8.11.1"
dom4j = "2.2.0"
kotlin = "2.2.0"
kotlinComposeCompilerPlugin = "2.1.20"
ksp = "2.2.0-2.0.2"
vico = "2.1.3"
hilt = "2.56.2"
androidXHilt = "1.2.0"
nav = "2.9.1"
coreKtx = "1.16.0"
splashscreen = "1.0.1"
lifecycle = "2.9.1"
activityCompose = "1.10.1"
composeBom = "2025.06.01"
composeMaterial3 = "1.3.2"
composeUi = "1.9.0"
composeAnimationGraphics = "1.9.0"
coil = "2.7.0"
jsoup = "1.21.1"
gson = "2.13.1"
markdown = "0.5.7"
ketch = "2.0.5"
room = "2.7.2"
work = "2.10.2"
desugar = "2.1.5"
junit = "4.13.2"
swipe = "1.3.0"
serializationJson = "1.9.0"
kotlinxCoroutinesCore = "1.10.2"
zoomableImageCoil = "0.16.0"

[libraries]
dom4j = { module = "org.dom4j:dom4j", version.ref = "dom4j" }
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "androidXHilt" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidXHilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidXHilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidXHilt" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
kotlin-compose-compiler-plugin = { module = "org.jetbrains.kotlin:kotlin-compose-compiler-plugin", version.ref = "kotlinComposeCompilerPlugin" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose-android", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "composeMaterial3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "composeUi" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUi" }
compose-animation-graphics = { module = "androidx.compose.animation:animation-graphics-android", version.ref = "composeAnimationGraphics" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
markdown = { module = "com.github.jeziellago:compose-markdown", version.ref = "markdown" }
ketch = { module = "com.github.khushpanchal:Ketch", version.ref = "ketch" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "nav" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
junit = { module = "junit:junit", version.ref = "junit" }
swipe = { module = "me.saket.swipe:swipe", version.ref = "swipe" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "zoomableImageCoil" }

[plugins]
kotlin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose_compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android_application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
google_dagger_hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google_ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
